# render.yaml
services:
  - type: web
    name: backend-depara
    env: node
    plan: free
    autoDeploy: true

    buildCommand: "npm install"
    startCommand: "node server.js"

    healthCheckPath: "/api/health"

    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
