services:
  - type: web
    name: backend-depara
    env: node
    buildCommand: npm install
    startCommand: node server.js
    plan: free
    autoDeploy: true
    healthCheckPath: /api/health
    envVars:
      NODE_ENV: production
